<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>AsyncChromeDriver.SeleniumAdapter</RootNamespace>
    <AssemblyName>AsyncChromeDriver.SeleniumAdapter</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>AsyncChromeDriver.SeleniumAdapter</PackageId>
    <Version>0.3.14</Version>
    <Title>AsyncChromeDriver.SeleniumAdapter</Title>
    <Authors>Oleg Zudov</Authors>
    <Company>Oleg Zudov</Company>
    <PackageLicenseUrl>https://github.com/ToCSharp/AsyncChromeDriverExamplesAndTests/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/ToCSharp/AsyncChromeDriverExamplesAndTests</PackageProjectUrl>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <Copyright>Copyright Oleg Zudov 2017</Copyright>
    <PackageTags>Chrome DevTools AsyncChromeDriver AsyncWebDriver WebDriver Selenium</PackageTags>
    <Description>Selenium Adapter for AsyncChromeDriver.</Description>
  </PropertyGroup>

  <ItemGroup>
    <!--Reference Include="System.Drawing" /-->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="WebSocket4Net" Version="0.15.2" />
    <PackageReference Include="AsyncChromeDriver" Version="0.3.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AsyncChromeDriver\AsyncChromeDriver\AsyncChromeDriver.csproj" />
    <ProjectReference Include="..\..\AsyncChromeDriver\ChromeDevToolsClient\ChromeDevToolsClient.csproj" />
    <ProjectReference Include="..\..\AsyncWebDriver\AsyncWebDriver\AsyncWebDriver.csproj" />
    <ProjectReference Include="..\..\IAsyncWebBrowserClient\IAsyncWebBrowserClient\IAsyncWebBrowserClient.csproj" />
    <ProjectReference Include="..\SeleniumAdapter\SeleniumAdapter.csproj" />
    <ProjectReference Include="..\SeleniumInterfaces\SeleniumInterfaces.csproj" />
  </ItemGroup>
</Project>